spring:
  application:
    name: spring-ai-alibaba-agent
  ai:
    dashscope:
      api-key: ${AliQwen_API}
    mcp:
      client:
        type: async
        request-timeout: 10s
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json

server:
  port: 8080
logging:
  level:
    com.alibaba.cloud.ai: debug
